server:
  port: 8080

spring:
  main:
    banner-mode: "off"
  application:
    name: server
  datasource:
    url: jdbc:mariadb://localhost:3306/demo_db
    password: Z$evdm#wiKV4P&
    username: demo_user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
